# Generated by Django 3.2 on 2024-01-03 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('bank_bik', models.CharField(max_length=25, verbose_name='БИК банка')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Название клиента')),
                ('client_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона')),
                ('client_address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('client_unp', models.CharField(max_length=150, verbose_name='УНП')),
                ('client_payment_code', models.CharField(max_length=255, verbose_name='Код платежа')),
                ('client_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.bank', verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, verbose_name='Hазвание страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(max_length=100, verbose_name='Номер по накладной')),
                ('expense_contract', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер договора')),
                ('expense_price', models.CharField(max_length=100, verbose_name='Стоимость')),
                ('expense_price_allowance', models.CharField(max_length=100, verbose_name='Стоимость с надбавкой')),
                ('currency', models.CharField(blank=True, max_length=100, null=True, verbose_name='Валюта')),
                ('expense_vat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сумма НДС ')),
                ('expense_date', models.DateField(verbose_name='Дата продажи')),
                ('number_proxy', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер доверенности')),
                ('date_proxy', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата доверенности')),
                ('proxy_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кем выдана довереннось')),
                ('expense_print', models.CharField(blank=True, max_length=100, null=True, verbose_name='Печатана ли накладная')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('group_level', models.CharField(blank=True, max_length=100, null=True, verbose_name='Уровень раздела')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_vendor_providers', models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикул товара поставщика ')),
                ('income_quantity', models.CharField(max_length=255, verbose_name='Количество')),
                ('product_country', models.CharField(max_length=255, verbose_name='Страна товара')),
                ('product_barcode', models.CharField(max_length=255, verbose_name='Штрихкод товара')),
                ('income_purchase_price', models.CharField(max_length=100, verbose_name='Закупочная цена')),
                ('income_price', models.CharField(max_length=100, verbose_name='Стоимость зак. цена * количество')),
                ('income_vat', models.CharField(max_length=255, verbose_name='НДС')),
                ('income_total_vat', models.CharField(max_length=100, verbose_name='Сумма НДС')),
                ('income_total_price_vat', models.CharField(max_length=100, verbose_name='Полная цена с ндс')),
                ('currency', models.CharField(blank=True, max_length=100, null=True, verbose_name='Валюта')),
                ('income_allowance', models.CharField(max_length=100, verbose_name='Надбавка')),
            ],
            options={
                'verbose_name': 'Приход',
                'verbose_name_plural': 'Приходы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название')),
                ('product_unit', models.CharField(max_length=10, verbose_name='Единица измерения')),
                ('product_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.CharField(max_length=255, verbose_name='Количество товара')),
                ('product_country', models.CharField(max_length=255, verbose_name='Страна товара')),
                ('product_vendor', models.CharField(max_length=255, verbose_name='Артикул товара')),
                ('product_reserve', models.CharField(max_length=255, verbose_name='Резерв товара')),
                ('product_price_provider', models.CharField(max_length=255, verbose_name='Цена с надбавкой')),
                ('expense_allowance', models.CharField(max_length=100, verbose_name='Надбавка')),
                ('product_price', models.CharField(max_length=255, verbose_name='Цена')),
                ('currency', models.CharField(blank=True, max_length=100, null=True, verbose_name='Валюта')),
                ('product_vat', models.CharField(max_length=255, verbose_name='НДС')),
                ('expense_full_price', models.CharField(blank=True, max_length=250, null=True, verbose_name='Общая цена с ндс')),
                ('product_barcode', models.CharField(max_length=255, verbose_name='Штрихкод')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.group', verbose_name='Группа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
            },
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_vendor', models.CharField(max_length=100, verbose_name='Артикул товара')),
                ('product_country', models.CharField(max_length=100, verbose_name='Страна товара')),
                ('product_barcode', models.CharField(max_length=100, verbose_name='Штрихкод товара')),
                ('product_vat', models.CharField(max_length=20, verbose_name='НДС')),
                ('product_extra', models.CharField(max_length=100, verbose_name='Надбавка')),
                ('product_quantity', models.CharField(max_length=100, verbose_name='Количество товара')),
                ('total_price_vat', models.CharField(max_length=100, verbose_name='Общая цена с НДС')),
                ('full_price', models.CharField(max_length=100, verbose_name='Общая цена с ндс и надбавкой')),
                ('currency', models.CharField(blank=True, max_length=100, null=True, verbose_name='Валюта')),
                ('date_item', models.DateField(verbose_name='Дата выставления чека')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.group', verbose_name='Группа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Розничная торговля',
                'verbose_name_plural': 'Розничная торговля',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=255, verbose_name='Название поставщика')),
                ('provider_phone', models.CharField(max_length=25, verbose_name='Номер телефона')),
                ('provider_address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('provider_unp', models.CharField(max_length=255, verbose_name='УНП')),
                ('provider_payment_code', models.CharField(max_length=255, verbose_name='Код платежа')),
                ('provider_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.bank', verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Price_change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_income', models.CharField(blank=True, max_length=100, null=True, verbose_name='Старая накладная')),
                ('price_change_date', models.CharField(max_length=100, verbose_name='Дата изменения цены')),
                ('expense_sale_price', models.CharField(max_length=100, verbose_name='Старая цена со склада')),
                ('price_change_new', models.CharField(max_length=100, verbose_name='Новая цена')),
                ('currency', models.CharField(blank=True, max_length=100, null=True, verbose_name='Валюта')),
                ('quantity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Количество')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.income', verbose_name='Накладная')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изменение цены',
                'verbose_name_plural': 'Изменение цены',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, verbose_name='Номер накладной')),
                ('product_date', models.DateField(verbose_name='Дата поступления ')),
                ('product_price', models.CharField(max_length=100, verbose_name='Цена по накладной')),
                ('currency', models.CharField(blank=True, max_length=100, null=True, verbose_name='Валюта')),
                ('product_price_nds', models.CharField(max_length=100, verbose_name='Цена с НДС')),
                ('providers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.provider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Накладная',
                'verbose_name_plural': 'Накладные',
            },
        ),
        migrations.AddField(
            model_name='income',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.invoice', verbose_name='Накладная'),
        ),
        migrations.AddField(
            model_name='income',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='income',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting_app.stock', verbose_name='Склад'),
        ),
        migrations.CreateModel(
            name='Expense_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_vendor', models.CharField(max_length=100, verbose_name='Артикул товара')),
                ('price_allowance', models.CharField(max_length=100, verbose_name='Цена с надбавкой')),
                ('price_mult_quant', models.CharField(max_length=100, verbose_name='Стоимость')),
                ('product_quantity', models.CharField(max_length=100, verbose_name='Количество товара для продажи')),
                ('amount_vat', models.CharField(max_length=100, verbose_name='Сумма НДС')),
                ('price_with_vat', models.CharField(max_length=100, verbose_name='Стоимость с НДС')),
                ('currency', models.CharField(blank=True, max_length=100, null=True, verbose_name='Валюта')),
                ('product_vat', models.CharField(max_length=20, verbose_name='НДС')),
                ('product_allowance', models.CharField(blank=True, max_length=100, null=True, verbose_name='Надбавка')),
                ('product_country', models.CharField(max_length=100, verbose_name='Страна товара')),
                ('product_barcode', models.CharField(max_length=100, verbose_name='Штрихкод товара')),
                ('product_discount', models.CharField(blank=True, max_length=100, null=True, verbose_name='Скидка')),
                ('product_stock', models.CharField(blank=True, max_length=100, null=True, verbose_name='Склад')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Примечание')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.expense', verbose_name='Расходная накладная')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.group', verbose_name='Группа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Расходная продажи',
                'verbose_name_plural': 'Расходная продажи',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, verbose_name='Номер договора')),
                ('contract_date', models.DateField(verbose_name='Дата договора')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.client', verbose_name='Kлиент')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договора',
            },
        ),
    ]
