# Generated by Django 4.2.5 on 2023-10-04 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('bank_bik', models.CharField(max_length=25, verbose_name='БИК банка')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Название клиента')),
                ('client_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона')),
                ('client_address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('client_unp', models.CharField(max_length=150, verbose_name='УНП')),
                ('client_payment_code', models.CharField(max_length=255, verbose_name='Код платежа')),
                ('client_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.bank', verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название')),
                ('product_vendor', models.CharField(max_length=255, verbose_name='Штрихкод')),
                ('product_allowance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Надбавка')),
                ('product_unit', models.CharField(max_length=10, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.CharField(max_length=100, verbose_name='Количество товара')),
                ('expense_allowance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена с надбавкой')),
                ('expense_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=255, verbose_name='Название поставщика')),
                ('provider_phone', models.CharField(max_length=25, verbose_name='Номер телефона')),
                ('provider_address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('provider_unp', models.CharField(max_length=255, verbose_name='УНП')),
                ('provider_payment_code', models.CharField(max_length=255, verbose_name='Код платежа')),
                ('provider_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.bank', verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Price_change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_change_date', models.DateField(blank=True, verbose_name='Дата изменения цены')),
                ('expense_sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Старая цена со склада')),
                ('price_change_new', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Новая цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изменение цены',
                'verbose_name_plural': 'Изменение цены',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, verbose_name='Номер накладной')),
                ('product_date', models.DateField(verbose_name='Дата поступления ')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена по накладной')),
                ('product_price_nds', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена с НДС')),
                ('providers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.provider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Накладная',
                'verbose_name_plural': 'Накладные',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('income_purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Закупочная цена')),
                ('income_nds', models.PositiveIntegerField(default=0, verbose_name='НДС')),
                ('product_country', models.CharField(max_length=255, verbose_name='Страна товара')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.invoice', verbose_name='Накладная')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Приход',
                'verbose_name_plural': 'Приходы',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(max_length=100, verbose_name='Номер накладной')),
                ('expense_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продажи')),
                ('expense_nds', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена с НДС ')),
                ('expense_date', models.DateField(verbose_name='Дата продажи')),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
            },
        ),
    ]
