# Generated by Django 3.2 on 2024-01-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
