# Generated by Django 4.2.5 on 2023-09-27 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_bank',
        ),
        migrations.AddField(
            model_name='client',
            name='bank',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.bank'),
            preserve_default=False,
        ),
    ]
