# Generated by Django 4.2.5 on 2023-11-08 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_change',
            name='income',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.income', verbose_name='Приход'),
            preserve_default=False,
        ),
    ]
