# Generated by Django 4.2.5 on 2023-09-27 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0002_remove_client_client_bank_client_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='provider_BIK',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='provider_bank',
        ),
        migrations.AddField(
            model_name='provider',
            name='bank',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.bank'),
            preserve_default=False,
        ),
    ]
