# Generated by Django 4.2.5 on 2023-11-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0002_price_change_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_change',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Количество'),
        ),
    ]
