# Generated by Django 4.2.5 on 2024-01-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип'),
        ),
    ]
