# Generated by Django 4.2.5 on 2024-01-10 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0003_expense_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='type',
            new_name='expense_type',
        ),
    ]
