# Generated by Django 4.2.5 on 2023-09-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0003_remove_provider_provider_bik_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_BIK',
        ),
    ]
