# Generated by Django 4.2.5 on 2023-10-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0003_expense_expense_price_allowance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expense_full_price',
        ),
    ]
