# Generated by Django 4.2.5 on 2023-09-27 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0004_remove_client_client_bik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_vendor',
        ),
    ]
