# Generated by Django 4.2.5 on 2023-10-10 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0004_remove_expense_expense_full_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_vat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сумма НДС '),
        ),
        migrations.AlterField(
            model_name='expense_item',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='expense_item',
            name='total_price_expense',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая цена с НДС, надбавкой и количеством'),
        ),
    ]
