# Generated by Django 4.2.5 on 2024-01-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0004_rename_type_expense_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_sum',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сумма'),
        ),
    ]
