# Generated by Django 4.2.5 on 2023-11-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0004_invoice_print'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='print',
        ),
    ]
