# Generated by Django 4.2.5 on 2023-09-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0005_remove_product_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_vendor',
            field=models.CharField(default=2, max_length=255, verbose_name='Артикул'),
            preserve_default=False,
        ),
    ]
