# Generated by Django 4.2.5 on 2023-10-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0005_alter_expense_expense_vat_alter_expense_item_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_item',
            name='price_provider',
            field=models.CharField(max_length=100, verbose_name='Цена поставщика'),
        ),
    ]
