# Generated by Django 4.2.5 on 2023-10-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0006_alter_expense_item_price_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_item',
            name='total_price_expense',
            field=models.CharField(max_length=100, verbose_name='Общая цена с НДС, надбавкой и количеством'),
        ),
    ]
