# Generated by Django 4.2.5 on 2023-10-02 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0006_product_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expense_quantity',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='expense_sale_price',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='product',
        ),
        migrations.AddField(
            model_name='expense',
            name='clients',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_number',
            field=models.IntegerField(default=0, verbose_name='Номер накладной'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10, verbose_name='Цена продажи'),
            preserve_default=False,
        ),
    ]
