# Generated by Django 4.2.5 on 2024-01-12 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0007_remove_contract_client_contract_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=100, verbose_name='Количество поступленных средств')),
                ('date', models.CharField(max_length=100, verbose_name='Дата поступления')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.provider', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Поступление средств',
                'verbose_name_plural': 'Поступления средств',
            },
        ),
        migrations.CreateModel(
            name='CashExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=100, verbose_name='Количество реализованных средств')),
                ('date', models.CharField(max_length=100, verbose_name='Дата реализации')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.provider', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Продажа услуг',
                'verbose_name_plural': 'Продажи услуг',
            },
        ),
    ]
