# Generated by Django 4.2.5 on 2023-10-02 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0007_remove_expense_expense_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.bank', verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_nds',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена с ндс '),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='providers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.provider', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='price_change',
            name='expense_sale_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.expense', verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='price_change',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.bank', verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.invoice', verbose_name='Накладная'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.product', verbose_name='Товар'),
        ),
    ]
