# Generated by Django 4.2.5 on 2023-10-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0007_alter_expense_item_total_price_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product_reserve',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Резерв товара'),
        ),
    ]
