# Generated by Django 4.2.5 on 2023-10-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0008_alter_client_bank_alter_expense_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата продажи'),
        ),
    ]
