# Generated by Django 4.2.5 on 2023-10-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0008_stock_product_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='expense_full_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая цена с ндс'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_price',
            field=models.PositiveIntegerField(verbose_name='Общая цена без ндс'),
        ),
    ]
