# Generated by Django 4.2.5 on 2023-11-28 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0008_alter_income_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting_app.stock', verbose_name='Склад'),
        ),
    ]
