# Generated by Django 4.2.5 on 2024-01-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0009_remove_cashinvoice_provider_delete_cashexpense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='provider_name',
            field=models.CharField(max_length=255, verbose_name='Наименование поставщика'),
        ),
    ]
