# Generated by Django 4.2.5 on 2023-10-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0009_alter_expense_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата продажи'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='product_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поступления товара'),
        ),
    ]
