# Generated by Django 4.2.5 on 2023-11-28 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0009_alter_income_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_change',
            name='old_income',
            field=models.CharField(default=2, max_length=100, verbose_name='Старая накладная'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price_change',
            name='income',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.income', verbose_name='Накладная'),
        ),
    ]
