# Generated by Django 4.2.5 on 2023-10-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0009_alter_stock_expense_full_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={},
        ),
        migrations.AlterField(
            model_name='stock',
            name='expense_full_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Общая цена с ндс'),
        ),
    ]
