# Generated by Django 4.2.5 on 2023-10-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0010_alter_stock_options_alter_stock_expense_full_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая цена без ндс'),
        ),
    ]
