# Generated by Django 4.2.5 on 2023-10-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0010_alter_expense_expense_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_change',
            name='price_change_date',
            field=models.DateField(verbose_name='Дата изменения цены'),
        ),
    ]
