# Generated by Django 4.2.5 on 2024-01-16 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0010_alter_provider_provider_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting_app.provider', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='income',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting_app.invoice', verbose_name='Накладная'),
        ),
        migrations.AlterField(
            model_name='income',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting_app.product', verbose_name='Товар'),
        ),
    ]
