# Generated by Django 4.2.5 on 2023-10-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0011_alter_price_change_price_change_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_change',
            name='stock',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.stock', verbose_name='Склад'),
            preserve_default=False,
        ),
    ]
