# Generated by Django 4.2.5 on 2023-11-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0011_rename_providers_invoice_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='provider',
            new_name='providers',
        ),
    ]
