# Generated by Django 4.2.5 on 2023-10-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0011_alter_stock_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product_price',
            field=models.CharField(max_length=100, verbose_name='Общая цена без ндс'),
        ),
    ]
