# Generated by Django 4.2.5 on 2023-12-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0012_rename_provider_invoice_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_change',
            name='old_income',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Старая накладная'),
        ),
    ]
