# Generated by Django 4.2.5 on 2023-10-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0012_alter_stock_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product_price',
            field=models.PositiveIntegerField(verbose_name='Общая цена без ндс'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_quantity',
            field=models.PositiveIntegerField(verbose_name='Количество товара'),
        ),
    ]
