# Generated by Django 4.2.5 on 2023-12-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0013_alter_price_change_old_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_proxy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата доверенности'),
        ),
    ]
