# Generated by Django 4.2.5 on 2024-01-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0013_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
