# Generated by Django 4.2.5 on 2023-10-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0013_alter_stock_product_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склад'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_price',
            field=models.CharField(max_length=255, verbose_name='Общая цена без ндс'),
        ),
    ]
