# Generated by Django 4.2.5 on 2023-10-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0013_alter_price_change_expense_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер накладной'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер накладной'),
        ),
    ]
