# Generated by Django 4.2.5 on 2023-10-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0014_alter_stock_options_alter_stock_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product_price',
            field=models.TextField(verbose_name='Общая цена без ндс'),
        ),
    ]
