# Generated by Django 4.2.5 on 2023-12-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0014_alter_expense_date_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_level',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Уровень раздела'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=100, verbose_name='Название группы'),
        ),
    ]
