# Generated by Django 4.2.5 on 2023-10-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0015_alter_expense_expense_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер накладной'),
        ),
    ]
