# Generated by Django 4.2.5 on 2023-10-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0016_alter_expense_expense_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='product_date',
            field=models.DateField(verbose_name='Дата поступления '),
        ),
    ]
