# Generated by Django 4.2.5 on 2023-12-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0016_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
