# Generated by Django 4.2.5 on 2023-10-12 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0016_alter_stock_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, verbose_name='Номер договора')),
                ('contract_date', models.DateField(verbose_name='Дата договора')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.client', verbose_name='Договор')),
            ],
        ),
    ]
