# Generated by Django 4.2.5 on 2023-10-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0017_alter_invoice_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_change',
            name='price_change_date',
            field=models.DateField(blank=True, verbose_name='Дата изменения цены'),
        ),
    ]
