# Generated by Django 4.2.5 on 2023-10-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0018_alter_contract_options_expense_date_proxy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='product_allowance',
            field=models.CharField(default=2, max_length=255, verbose_name='Надбавка'),
            preserve_default=False,
        ),
    ]
