# Generated by Django 4.2.5 on 2023-10-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0019_income_product_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product_price_provider',
            field=models.CharField(default=2, max_length=255, verbose_name='Цена без надбавки'),
            preserve_default=False,
        ),
    ]
