# Generated by Django 4.2.5 on 2023-10-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0021_rename_product_allowance_income_income_allowance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='income_total_price_vatt',
            new_name='income_total_price_vat',
        ),
    ]
