# Generated by Django 4.2.5 on 2023-10-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0022_rename_income_total_price_vatt_income_income_total_price_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income_total_price_vat',
            field=models.CharField(max_length=255, verbose_name='Полная цена с ндс'),
        ),
    ]
