# Generated by Django 4.2.5 on 2023-10-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0023_alter_income_income_total_price_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income_allowance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Надбавка'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость зак. цена * количество'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_total_price_vat',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Полная цена с ндс'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_total_vat',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма НДС'),
        ),
    ]
