# Generated by Django 4.2.5 on 2023-10-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0024_alter_income_income_allowance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income_quantity',
            field=models.CharField(max_length=255, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_vat',
            field=models.CharField(max_length=255, verbose_name='НДС'),
        ),
    ]
