# Generated by Django 4.2.5 on 2023-10-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0025_alter_income_income_quantity_alter_income_income_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_price',
            field=models.CharField(max_length=100, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_price_allowance',
            field=models.CharField(max_length=100, verbose_name='Стоимость с надбавкой'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_allowance',
            field=models.CharField(max_length=100, verbose_name='Надбавка'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_price',
            field=models.CharField(max_length=100, verbose_name='Стоимость зак. цена * количество'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_purchase_price',
            field=models.CharField(max_length=100, verbose_name='Закупочная цена'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_total_price_vat',
            field=models.CharField(max_length=100, verbose_name='Полная цена с ндс'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_total_vat',
            field=models.CharField(max_length=100, verbose_name='Сумма НДС'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='product_price',
            field=models.CharField(max_length=100, verbose_name='Цена по накладной'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='product_price_nds',
            field=models.CharField(max_length=100, verbose_name='Цена с НДС'),
        ),
        migrations.AlterField(
            model_name='price_change',
            name='expense_sale_price',
            field=models.CharField(max_length=100, verbose_name='Старая цена со склада'),
        ),
        migrations.AlterField(
            model_name='price_change',
            name='price_change_new',
            field=models.CharField(max_length=100, verbose_name='Новая цена'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='full_price',
            field=models.CharField(max_length=100, verbose_name='Общая цена с ндс и надбавкой'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='total_price_vat',
            field=models.CharField(max_length=100, verbose_name='Общая цена с НДС'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='expense_allowance',
            field=models.CharField(max_length=100, verbose_name='Надбавка'),
        ),
    ]
