# Generated by Django 4.2.5 on 2023-10-16 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0026_alter_expense_expense_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense_item',
            name='product_extra',
        ),
    ]
