# Generated by Django 4.2.5 on 2023-10-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0027_remove_expense_item_product_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense_item',
            name='price_provider',
        ),
        migrations.RemoveField(
            model_name='expense_item',
            name='total_price_expense',
        ),
        migrations.AddField(
            model_name='expense_item',
            name='amount_vat',
            field=models.CharField(default=2, max_length=100, verbose_name='Сумма НДС'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense_item',
            name='price_allowance',
            field=models.CharField(default=2, max_length=100, verbose_name='Цена с надбавкой'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense_item',
            name='price_mult_quant',
            field=models.CharField(default=2, max_length=100, verbose_name='Стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense_item',
            name='price_with_vat',
            field=models.CharField(default=2, max_length=100, verbose_name='Стоимость с НДС'),
            preserve_default=False,
        ),
    ]
