# Generated by Django 4.2.5 on 2023-10-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0028_remove_expense_item_price_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_proxy',
            field=models.CharField(default=2, max_length=100, verbose_name='Дата доверенности'),
            preserve_default=False,
        ),
    ]
