# Generated by Django 4.2.5 on 2023-10-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0029_alter_expense_date_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_item',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Примечание'),
        ),
    ]
