# Generated by Django 4.2.5 on 2023-10-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0030_expense_item_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product_reserve',
            field=models.CharField(default=2, max_length=255, verbose_name='Резерв товара'),
            preserve_default=False,
        ),
    ]
