# Generated by Django 4.2.5 on 2023-10-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0031_alter_stock_product_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_change',
            name='price_change_date',
            field=models.CharField(max_length=100, verbose_name='Дата изменения цены'),
        ),
    ]
