# Generated by Django 4.2.5 on 2023-10-19 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0033_country_alter_stock_expense_full_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name_country',
            new_name='country_name',
        ),
    ]
